apiVersion: v1
kind: ConfigMap
metadata:
  name:         "zerotier-{{ .Values.environment }}-{{ .Release.Name }}"
  namespace:    {{ .Release.Namespace }}
  labels:
    network:    {{ .Values.config.networkName }}
    service:    {{ .Values.config.labelService }}
data:
  NETWORK-IDS:  {{ .Values.config.networkId }}
  ZTAUTHTOKEN:  {{ .Values.config.accessToken }}
  AUTOJOIN:     "{{ .Values.config.authorizeMember }}"
  ZTHOSTNAME:   "{{ .Values.environment }}_out"
