{{- if .Values.persistentVolume.enabled }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ztdata
spec:
  accessModes:
{{ toYaml .Values.persistentVolume.accessModes | indent 4 }}
  resources:
    requests:
      storage: "{{ .Values.persistentVolume.size }}"
  {{- if .Values.persistentVolume.storageClass }}
  {{- if (eq "-" .Values.persistentVolume.storageClass) }}
  storageClassName: ""
  {{- else }}
  storageClassName: "{{ .Values.persistentVolume.storageClass }}"
  {{- end }}
  {{- end }}
{{- end }}