environment: "dummy"

zerotier_config:
  zerotier_network_id: "1abcdf,2abcdf,3abcdf"
  zerotier_network_name: "example"
  zerotier_api_accesstoken: "abcdf1234567890"
  zerotier_authorize_member: true
  zerotier_label_service: "zerotier"

image:
  repository: leonardoventurini/k8s-zerotier-bridge
  tag: latest
  pullPolicy: IfNotPresent

resources:
  limits:
    cpu: 0.8
    memory: 512Mi
  requests:
    cpu: 0.1
    memory: 64Mi

persistentVolume:
  enabled: false
  accessModes:
    - ReadWriteOnce
  annotations: {}
  mountPath: /var/lib/zerotier-one
  size: 1Gi
