environment: "production"

config:
  networkId: "1abcdf,2abcdf,3abcdf"
  networkName: "example"
  accessToken: "abcdf1234567890"
  authorizeMember: true
  labelService: "zerotier"

image:
  repository: leonardoventurini/k8s-zerotier-bridge
  tag: latest
  pullPolicy: IfNotPresent

resources:
  limits:
    cpu: 0.8
    memory: 512Mi
  requests:
    cpu: 0.1
    memory: 64Mi

persistentVolume:
  enabled: false
  accessModes:
    - ReadWriteOnce
  annotations: {}
  mountPath: /var/lib/zerotier-one
  size: 1Gi
